version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:817827901549:task-definition/backend-app:1
        LoadBalancerInfo:
          ContainerName: backend-app
          ContainerPort: 80