version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ECR_REPO_URI: 817827901549.dkr.ecr.us-east-1.amazonaws.com/fastapi-app

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 817827901549.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t fastapi-app -f application/Dockerfile application
      - docker tag fastapi-app:latest $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push $ECR_REPO_URI:latest
      - printf '[{"name":"backend-api","imageUri":"%s"}]' $ECR_REPO_URI:latest > imagedefinitions.json

artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json